const db = require('./db');
const bcrypt = require('bcrypt');

async function initializeDatabase() {
    const primaryKey = db.USE_POSTGRES
        ? 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY'
        : 'INTEGER PRIMARY KEY';

    // USERS
    await db.query(`
        CREATE TABLE IF NOT EXISTS users (
            id ${primaryKey},

            account_number TEXT UNIQUE,

            first_name TEXT NOT NULL,
            last_name TEXT NOT NULL,

            username TEXT UNIQUE,

            email TEXT UNIQUE NOT NULL,
            phone TEXT,

            password TEXT NOT NULL,

            login_code_hash TEXT,

            email_verified INTEGER DEFAULT 0,

            gender TEXT,
            date_of_birth TEXT,

            country TEXT,
            state TEXT,
            zip_code TEXT,

            marital_status TEXT,

            occupation TEXT,
            address TEXT,

            government_id_number TEXT,

            kyc_status TEXT DEFAULT 'PENDING',

           id_front_image TEXT,

           id_back_image TEXT,

            profile_image TEXT,

            preferred_currency TEXT DEFAULT 'USD',

            account_type TEXT DEFAULT 'CHECKING',

            balance REAL DEFAULT 0,

            transfer_pin TEXT,

            
          transfer_otp TEXT,

        preferred_language TEXT DEFAULT 'en',

          transfer_flow TEXT DEFAULT 'PENDING',

          

          

            two_factor_enabled INTEGER DEFAULT 0,

            status TEXT DEFAULT 'ACTIVE',

            role TEXT DEFAULT 'USER',

            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    `);

    // SESSIONS
    await db.query(`
        CREATE TABLE IF NOT EXISTS deposit_requests (
            id ${primaryKey}, user_id INTEGER NOT NULL, method TEXT NOT NULL,
            account_id INTEGER,
            amount REAL NOT NULL, card_name TEXT, bitcoin_address TEXT,
            images_json TEXT, status TEXT DEFAULT 'PENDING',
            created_at TEXT DEFAULT CURRENT_TIMESTAMP, updated_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    `);

    try {
        await db.query(`ALTER TABLE users ADD COLUMN account_type TEXT DEFAULT 'CHECKING'`);
    } catch (_) {
        // Compatibility with databases that already have this column.
    }

    await db.query(`
        CREATE TABLE IF NOT EXISTS sessions (
            id ${primaryKey},

            user_id INTEGER NOT NULL,

            token TEXT UNIQUE NOT NULL,

            expires_at TEXT NOT NULL,

            attempts INTEGER DEFAULT 0,

            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    `);

    // TRANSFERS
    await db.query(`
CREATE TABLE IF NOT EXISTS transfers (
    id ${primaryKey},

    sender_id INTEGER NOT NULL,

    transfer_type TEXT NOT NULL,

    recipient_user_id INTEGER,

    recipient_account_number TEXT,

    recipient_name TEXT,

    recipient_bank TEXT,

    amount REAL NOT NULL,

    currency TEXT DEFAULT 'USD',

    status TEXT DEFAULT 'PENDING',

    description TEXT,

    approved_by INTEGER,

    

    created_at TEXT DEFAULT CURRENT_TIMESTAMP,

    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
)
`);


    // Transfers






    // ACTIVITIES
    await db.query(`
        CREATE TABLE IF NOT EXISTS activities (
            id ${primaryKey},

            user_id INTEGER,

            type TEXT NOT NULL,

            description TEXT NOT NULL,

            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    `);

    // NOTIFICATIONS
    await db.query(`
        CREATE TABLE IF NOT EXISTS notifications (
            id ${primaryKey},

            user_id INTEGER NOT NULL,

            title TEXT NOT NULL,

            message TEXT NOT NULL,

            type TEXT DEFAULT 'INFO',

            action_link TEXT,

            is_read INTEGER DEFAULT 0,

            created_by INTEGER,

            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await db.query(`
        CREATE TABLE IF NOT EXISTS login_challenges (
            id ${primaryKey},
            user_id INTEGER NOT NULL,
            token TEXT UNIQUE NOT NULL,
            purpose TEXT NOT NULL DEFAULT 'LOGIN',
            attempts INTEGER DEFAULT 0,
            expires_at TEXT NOT NULL,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await db.query(`CREATE TABLE IF NOT EXISTS support_conversations (
        id ${primaryKey}, user_id INTEGER NOT NULL UNIQUE, status TEXT DEFAULT 'OPEN',
        last_message_at TEXT DEFAULT CURRENT_TIMESTAMP, created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`);
    await db.query(`CREATE TABLE IF NOT EXISTS support_messages (
        id ${primaryKey}, conversation_id INTEGER NOT NULL, sender_id INTEGER NOT NULL,
        sender_role TEXT NOT NULL, message TEXT NOT NULL, is_read INTEGER DEFAULT 0,
        created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`);
    await db.query(`CREATE TABLE IF NOT EXISTS push_subscriptions (
        id ${primaryKey}, user_id INTEGER NOT NULL, endpoint TEXT NOT NULL UNIQUE,
        p256dh TEXT NOT NULL, auth TEXT NOT NULL, created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`);
    await db.query(`CREATE TABLE IF NOT EXISTS app_settings (
        setting_key TEXT PRIMARY KEY, setting_value TEXT NOT NULL, updated_at TEXT DEFAULT CURRENT_TIMESTAMP
    )`);

    await db.query(`
        CREATE TABLE IF NOT EXISTS email_settings (
            id ${primaryKey},
            smtp_host TEXT,
            smtp_port INTEGER,
            smtp_username TEXT,
            smtp_password_encrypted TEXT,
            smtp_secure INTEGER DEFAULT 0,
            sender_email TEXT,
            sender_name TEXT,
            updated_by INTEGER,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await db.query(`
        CREATE TABLE IF NOT EXISTS email_logs (
            id ${primaryKey},
            recipient_user_id INTEGER,
            recipient_email TEXT NOT NULL,
            subject TEXT NOT NULL,
            status TEXT NOT NULL,
            provider_message_id TEXT,
            error_message TEXT,
            sent_by INTEGER,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            sent_at TEXT
        )
    `);

    await db.query(`
        CREATE TABLE IF NOT EXISTS withdrawal_destinations (
            id ${primaryKey},
            user_id INTEGER NOT NULL,
            method TEXT NOT NULL,
            label TEXT NOT NULL,
            details_json TEXT NOT NULL,
            is_preferred INTEGER DEFAULT 0,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await db.query(`
        CREATE TABLE IF NOT EXISTS withdrawal_requests (
            id ${primaryKey},
            user_id INTEGER NOT NULL,
            destination_id INTEGER,
            method TEXT NOT NULL,
            amount REAL NOT NULL,
            currency TEXT NOT NULL,
            destination_snapshot_json TEXT NOT NULL,
            status TEXT DEFAULT 'PENDING',
            reference TEXT UNIQUE NOT NULL,
            note TEXT,
            reviewed_by INTEGER,
            reviewed_at TEXT,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await db.query(`
        CREATE TABLE IF NOT EXISTS withdrawal_accounts (
            id ${primaryKey},
            user_id INTEGER NOT NULL,
            method TEXT NOT NULL,
            username TEXT NOT NULL,
            display_name TEXT,
            details_json TEXT,
            destination_id INTEGER,
            linked INTEGER DEFAULT 1,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(user_id, method, username)
        )
    `);

    const forbiddenWithdrawalFields = new Set([
        'password', 'bank_password', 'paypal_password', 'passcode', 'pin',
        'card_pin', 'cvv', 'cvc', 'security_code', 'card_number', 'full_card_number'
    ]);

    for (const table of ['withdrawal_destinations', 'withdrawal_accounts']) {
        const rows = await db.query(`SELECT id, details_json FROM ${table}`);
        for (const row of rows) {
            try {
                const details = JSON.parse(row.details_json || '{}');
                let changed = false;
                for (const field of Object.keys(details)) {
                    if (forbiddenWithdrawalFields.has(field.toLowerCase())) {
                        delete details[field];
                        changed = true;
                    }
                }
                if (changed) {
                    await db.query(
                        `UPDATE ${table} SET details_json = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?`,
                        [JSON.stringify(details), row.id]
                    );
                }
            } catch {
                // Existing malformed records remain unavailable until corrected by an administrator.
            }
        }
    }

    const requestSnapshots = await db.query(`SELECT id, destination_snapshot_json FROM withdrawal_requests`);
    for (const row of requestSnapshots) {
        try {
            const details = JSON.parse(row.destination_snapshot_json || '{}');
            let changed = false;
            for (const field of Object.keys(details)) {
                if (forbiddenWithdrawalFields.has(field.toLowerCase())) {
                    delete details[field];
                    changed = true;
                }
            }
            if (changed) {
                await db.query(
                    `UPDATE withdrawal_requests SET destination_snapshot_json = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?`,
                    [JSON.stringify(details), row.id]
                );
            }
        } catch {
            // Existing malformed records remain unavailable until corrected by an administrator.
        }
    }

    await db.query(`
        CREATE TABLE IF NOT EXISTS transfer_verification_codes (
            id ${primaryKey},
            user_id INTEGER NOT NULL,
            code_hash TEXT NOT NULL,
            code_last_four TEXT NOT NULL,
            status TEXT DEFAULT 'ACTIVE',

            account_type TEXT DEFAULT 'CHECKING',
            created_by INTEGER NOT NULL,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
            revoked_at TEXT
        )
    `);

    await db.query(`
        CREATE TABLE IF NOT EXISTS transfer_verification_attempts (
            id ${primaryKey},
            user_id INTEGER NOT NULL,
            code_id INTEGER,
            success INTEGER DEFAULT 0,
            ip_address TEXT,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await db.query(`
        CREATE TABLE IF NOT EXISTS transfer_verification_sessions (
            id ${primaryKey},
            user_id INTEGER NOT NULL,
            code_id INTEGER NOT NULL,
            token TEXT UNIQUE NOT NULL,
            expires_at TEXT NOT NULL,
            used_at TEXT,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await db.query(`
        CREATE TABLE IF NOT EXISTS password_reset_tokens (
            id ${primaryKey},
            user_id INTEGER NOT NULL,
            token_hash TEXT NOT NULL,
            expires_at TEXT NOT NULL,
            used_at TEXT,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    `);

    // EMAIL VERIFICATIONS
    await db.query(`
        CREATE TABLE IF NOT EXISTS email_verifications (
            id ${primaryKey},

            user_id INTEGER NOT NULL,

            token TEXT UNIQUE NOT NULL,

            expires_at TEXT NOT NULL,

            created_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await db.query(`
    CREATE TABLE IF NOT EXISTS transactions (
        id ${primaryKey},

        user_id INTEGER NOT NULL,

        reference TEXT UNIQUE,

        type TEXT NOT NULL,

        category TEXT,

        amount REAL NOT NULL,

        currency TEXT DEFAULT 'USD',

        status TEXT DEFAULT 'COMPLETED',

        description TEXT,

        created_by INTEGER,
        
        transaction_date TEXT,

        origin_name TEXT,

        origin_bank TEXT,

        origin_account_number TEXT,

        created_at TEXT DEFAULT CURRENT_TIMESTAMP
    )
`);

    await db.query(`
CREATE TABLE IF NOT EXISTS loans (

    id ${primaryKey},

    user_id INTEGER NOT NULL,

    requested_amount REAL NOT NULL,

    purpose TEXT,

    interest_rate REAL DEFAULT 0,

    repayment_months INTEGER DEFAULT 12,

    monthly_payment REAL,

    disbursement_fee REAL DEFAULT 0,

fee_status TEXT DEFAULT 'UNPAID'
CHECK(fee_status IN (
    'UNPAID',
    'PAID',
    'WAIVED'
)),


   status TEXT DEFAULT 'PENDING'
CHECK(status IN (
   'PENDING',

    'APPROVED',

    'AWAITING_DISBURSEMENT_FEE',

    'READY_FOR_DISBURSEMENT',

    'DISBURSED',

    'REJECTED'
)),

    approved_by INTEGER,

    approved_at TEXT,

    created_at TEXT DEFAULT CURRENT_TIMESTAMP
)
`);

    await db.query(`
CREATE TABLE IF NOT EXISTS banks (

    id ${primaryKey},

    country TEXT NOT NULL,

    bank_name TEXT NOT NULL,

    bank_code TEXT,

    status TEXT DEFAULT 'ACTIVE',

    created_at TEXT DEFAULT CURRENT_TIMESTAMP
)
`);



    await db.query(`
CREATE TABLE IF NOT EXISTS cards (

    id ${primaryKey},

    user_id INTEGER NOT NULL,

    card_type TEXT DEFAULT 'VISA DEBIT',

    card_number TEXT,

    expiry_date TEXT,

    cvv TEXT,

    cardholder_name TEXT,

    delivery_address TEXT,

    issuance_fee REAL DEFAULT 0,

    purchase_limit_min REAL DEFAULT 0,

    purchase_limit_max REAL DEFAULT 0,

    shipping_included INTEGER DEFAULT 0,

    txn_reference_image TEXT,

    txn_reference_mime TEXT,

    txn_reference_uploaded_at TEXT,

    payment_status TEXT DEFAULT 'UNPAID',

    status TEXT DEFAULT 'PENDING',

    approved_by INTEGER,

    approved_at TEXT,

    payment_confirmed_at TEXT,

    released_at TEXT,

    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,

    created_at TEXT DEFAULT CURRENT_TIMESTAMP
)
`);

    // ACCOUNTS + OWNERSHIP
    // users.account_number/balance remain as compatibility mirrors while all
    // ownership is represented here, allowing one account to have many owners.
    await db.query(`
        CREATE TABLE IF NOT EXISTS accounts (
            id ${primaryKey},
            account_number TEXT UNIQUE NOT NULL,
            account_type TEXT NOT NULL DEFAULT 'CHECKING',
            account_kind TEXT NOT NULL DEFAULT 'PRIMARY',
            currency TEXT DEFAULT 'USD',
            balance REAL DEFAULT 0,
            status TEXT DEFAULT 'ACTIVE',
            approval_threshold REAL,
            approval_mode INTEGER DEFAULT 0,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            updated_at TEXT DEFAULT CURRENT_TIMESTAMP
        )
    `);

    await db.query(`
        CREATE TABLE IF NOT EXISTS account_owners (
            id ${primaryKey},
            account_id INTEGER NOT NULL,
            user_id INTEGER NOT NULL,
            role TEXT NOT NULL DEFAULT 'JOINT_OWNER',
            status TEXT NOT NULL DEFAULT 'PENDING',
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            UNIQUE(account_id, user_id)
        )
    `);

    await db.query(`
        CREATE TABLE IF NOT EXISTS joint_account_invitations (
            id ${primaryKey},
            account_id INTEGER NOT NULL,
            invited_by INTEGER NOT NULL,
            invitee_user_id INTEGER,
            email TEXT,
            phone TEXT,
            customer_id TEXT,
            username TEXT,
            requires_kyc INTEGER DEFAULT 0,
            token TEXT UNIQUE NOT NULL,
            status TEXT NOT NULL DEFAULT 'PENDING',
            expires_at TEXT NOT NULL,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            responded_at TEXT
        )
    `);

    const cardColumns = [
        `ALTER TABLE cards ADD COLUMN cardholder_name TEXT`,
        `ALTER TABLE cards ADD COLUMN delivery_address TEXT`,
        `ALTER TABLE cards ADD COLUMN issuance_fee REAL DEFAULT 0`,
        `ALTER TABLE cards ADD COLUMN purchase_limit_min REAL DEFAULT 0`,
        `ALTER TABLE cards ADD COLUMN purchase_limit_max REAL DEFAULT 0`,
        `ALTER TABLE cards ADD COLUMN shipping_included INTEGER DEFAULT 0`,
        `ALTER TABLE cards ADD COLUMN txn_reference_image TEXT`,
        `ALTER TABLE cards ADD COLUMN txn_reference_mime TEXT`,
        `ALTER TABLE cards ADD COLUMN txn_reference_uploaded_at TEXT`,
        `ALTER TABLE cards ADD COLUMN payment_status TEXT DEFAULT 'UNPAID'`,
        `ALTER TABLE cards ADD COLUMN approved_by INTEGER`,
        `ALTER TABLE cards ADD COLUMN approved_at TEXT`,
        `ALTER TABLE cards ADD COLUMN payment_confirmed_at TEXT`,
        `ALTER TABLE cards ADD COLUMN released_at TEXT`,
        `ALTER TABLE cards ADD COLUMN updated_at TEXT`
    ];

    for (const statement of cardColumns) {
        try {
            await db.query(statement);
        } catch (e) {
            // Compatibility with databases created before card applications.
        }
    }

    const sharedAccountColumns = [
        `ALTER TABLE transactions ADD COLUMN account_id INTEGER`,
        `ALTER TABLE transactions ADD COLUMN performed_by INTEGER`,
        `ALTER TABLE accounts ADD COLUMN account_kind TEXT DEFAULT 'PRIMARY'`,
        `ALTER TABLE deposit_requests ADD COLUMN account_id INTEGER`,
        `ALTER TABLE joint_account_invitations ADD COLUMN requires_kyc INTEGER DEFAULT 0`
    ];

    for (const statement of sharedAccountColumns) {
        try {
            await db.query(statement);
        } catch (e) {
            // Compatibility with databases already using account attribution.
        }
    }

    const transactionOriginColumns = [
        `ALTER TABLE transactions ADD COLUMN origin_name TEXT`,
        `ALTER TABLE transactions ADD COLUMN origin_bank TEXT`,
        `ALTER TABLE transactions ADD COLUMN origin_account_number TEXT`
    ];
    for (const statement of transactionOriginColumns) {
        try {
            await db.query(statement);
        } catch (_error) {
            // Compatibility with databases where the origin columns already exist.
        }
    }

    // Give every existing user a primary account without changing any account
    // number or balance. This migration is idempotent on SQLite and Postgres.
    const existingUsers = await db.query(`
        SELECT id, account_number, account_type, preferred_currency, balance
        FROM users
        WHERE account_number IS NOT NULL AND account_number != ''
    `);

    for (const user of existingUsers) {
        let account = (await db.query(`SELECT * FROM accounts WHERE account_number = ?`, [user.account_number]))[0];

        if (!account) {
            if (db.USE_POSTGRES) {
                account = (await db.query(`
                    INSERT INTO accounts (account_number, account_type, currency, balance)
                    VALUES (?, ?, ?, ?) RETURNING *
                `, [user.account_number, user.account_type || 'CHECKING', user.preferred_currency || 'USD', Number(user.balance || 0)]))[0];
            } else {
                await db.query(`
                    INSERT INTO accounts (account_number, account_type, currency, balance)
                    VALUES (?, ?, ?, ?)
                `, [user.account_number, user.account_type || 'CHECKING', user.preferred_currency || 'USD', Number(user.balance || 0)]);
                account = (await db.query(`SELECT * FROM accounts WHERE account_number = ?`, [user.account_number]))[0];
            }
        }

        const owner = (await db.query(`SELECT id FROM account_owners WHERE account_id = ? AND user_id = ?`, [account.id, user.id]))[0];
        if (!owner) {
            await db.query(`
                INSERT INTO account_owners (account_id, user_id, role, status)
                VALUES (?, ?, 'PRIMARY_OWNER', 'ACCEPTED')
            `, [account.id, user.id]);
        }
    }

    await db.query(`
        UPDATE transactions
        SET account_id = (
            SELECT ao.account_id FROM account_owners ao
            WHERE ao.user_id = transactions.user_id AND ao.role = 'PRIMARY_OWNER'
            ORDER BY ao.id ASC LIMIT 1
        ),
        performed_by = COALESCE(performed_by, created_by, user_id)
        WHERE account_id IS NULL
    `);

    const indexes = [
        `CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at)`,
        `CREATE INDEX IF NOT EXISTS idx_users_role ON users(role)`,
        `CREATE INDEX IF NOT EXISTS idx_transactions_user_id_id ON transactions(user_id, id)`,
        `CREATE INDEX IF NOT EXISTS idx_transactions_id ON transactions(id)`,
        `CREATE INDEX IF NOT EXISTS idx_transactions_account_id_id ON transactions(account_id, id)`,
        `CREATE INDEX IF NOT EXISTS idx_account_owners_user_id ON account_owners(user_id)`,
        `CREATE INDEX IF NOT EXISTS idx_account_owners_account_id ON account_owners(account_id)`,
        `CREATE INDEX IF NOT EXISTS idx_joint_invitations_invitee ON joint_account_invitations(invitee_user_id, status)`,
        `CREATE INDEX IF NOT EXISTS idx_transfers_sender_id ON transfers(sender_id)`,
        `CREATE INDEX IF NOT EXISTS idx_transfers_recipient_user_id ON transfers(recipient_user_id)`,
        `CREATE INDEX IF NOT EXISTS idx_transfers_status_id ON transfers(status, id)`,
        `CREATE INDEX IF NOT EXISTS idx_loans_user_id_id ON loans(user_id, id)`,
        `CREATE INDEX IF NOT EXISTS idx_cards_user_id_id ON cards(user_id, id)`
    ];

    for (const indexSql of indexes) {
        await db.query(indexSql);
    }







    const adminPassword =
        await bcrypt.hash(
            'Admin123',
            10
        );

    const adminSeedSql = db.USE_POSTGRES
        ? `
    INSERT INTO users (
        id,
        account_number,
        first_name,
        last_name,
        username,
        email,
        phone,
        password,
        role,
        status
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ON CONFLICT (id) DO NOTHING
    `
        : `
    INSERT OR IGNORE INTO users (
        id,
        account_number,
        first_name,
        last_name,
        username,
        email,
        phone,
        password,
        role,
        status
    )
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `;

    await db.query(
        adminSeedSql,
        [
            1,
            '1000000001',
            'System',
            'Admin',
            'admin',
            'admin@bank.com',
            '+10000000000',
            adminPassword,
            'ADMIN',
            'ACTIVE'
        ]
    );





    try {
        await db.query(`ALTER TABLE users ADD COLUMN two_factor_enabled INTEGER DEFAULT 0`);
    } catch (e) {
        // Column might already exist, ignore error
    }

    const notificationColumns = [
        `ALTER TABLE notifications ADD COLUMN type TEXT DEFAULT 'INFO'`,
        `ALTER TABLE notifications ADD COLUMN action_link TEXT`,
        `ALTER TABLE notifications ADD COLUMN created_by INTEGER`
    ];

    const userSecurityColumns = [
        `ALTER TABLE users ADD COLUMN force_password_change INTEGER DEFAULT 0`,
        `ALTER TABLE users ADD COLUMN password_changed_at TEXT`,
        `ALTER TABLE users ADD COLUMN login_code_hash TEXT`,
        `ALTER TABLE login_challenges ADD COLUMN purpose TEXT DEFAULT 'LOGIN'`
    ];

    const emailVerificationColumns = [
        `ALTER TABLE email_verifications ADD COLUMN attempts INTEGER DEFAULT 0`
    ];

    for (const statement of userSecurityColumns) {
        try {
            await db.query(statement);
        } catch (e) {
            // Compatibility with existing databases.
        }
    }

    for (const statement of emailVerificationColumns) {
        try {
            await db.query(statement);
        } catch (e) {
            // Compatibility with databases that already have this protection.
        }
    }

    await db.query(`
        UPDATE transactions
        SET category = CASE WHEN type = 'CREDIT' THEN 'deposit' ELSE 'account_debit' END,
            description = CASE WHEN type = 'CREDIT' THEN 'Account Deposit' ELSE 'Account Debit' END
        WHERE category IN ('admin_balance_adjustment', 'balance_adjustment')
           OR description LIKE 'Admin balance adjusted to %'
    `);

    await db.query(`
        UPDATE transactions
        SET category = CASE WHEN type = 'CREDIT' THEN 'deposit' ELSE 'account_debit' END,
            description = CASE
                WHEN description IS NULL
                  OR description = ''
                  OR description IN ('Manual System Adjustment', 'Batch System Adjustment')
                  THEN CASE WHEN type = 'CREDIT' THEN 'Account Deposit' ELSE 'Account Debit' END
                ELSE description
            END
        WHERE category = 'manual_entry'
           OR category = 'Manual Entry'
    `);

    try {
        await db.query(`ALTER TABLE transfers ADD COLUMN verification_code_id INTEGER`);
    } catch (e) {
        // Compatibility with existing databases.
    }

    for (const statement of notificationColumns) {
        try {
            await db.query(statement);
        } catch (e) {
            // Compatibility for databases created before notification metadata.
        }
    }

    console.log('Database initialized');
}

module.exports = initializeDatabase;
